-- ============================================================================
-- MyEzz Complete Database Schema
-- This file contains ALL your existing schema + the new additions for backend
-- ============================================================================

-- ============================================================================
-- SECTION 1: YOUR EXISTING SCHEMA (For Reference - Already Created)
-- ============================================================================

-- 1. Master table for Cuisines
-- CREATE TABLE cuisines (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name TEXT NOT NULL UNIQUE
-- );

-- 2. Master table for Tags
-- CREATE TABLE tags (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name TEXT NOT NULL UNIQUE
-- );

-- 3. Master table for Categories
-- CREATE TABLE categories (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name TEXT NOT NULL UNIQUE,
--   image_url TEXT,
--   keywords TEXT[]
-- );

-- 4. Main Restaurants Table
-- CREATE TABLE restaurants (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name TEXT NOT NULL,
--   distance NUMERIC,
--   rating NUMERIC(2, 1),
--   reviews INT,
--   delivery_time TEXT,
--   image_url TEXT,
--   offer TEXT,
--   operating_hours TEXT
-- );

-- 5. Menu Items Table
-- CREATE TABLE menu_items (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name TEXT NOT NULL,
--   price NUMERIC(10, 2) NOT NULL,
--   is_veg BOOLEAN DEFAULT TRUE,
--   restaurant_id BIGINT REFERENCES restaurants(id) ON DELETE CASCADE,
--   category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL
-- );

-- 6. Join Table for Restaurants and Cuisines
-- CREATE TABLE restaurant_cuisines (
--   restaurant_id BIGINT REFERENCES restaurants(id) ON DELETE CASCADE,
--   cuisine_id BIGINT REFERENCES cuisines(id) ON DELETE CASCADE,
--   PRIMARY KEY (restaurant_id, cuisine_id)
-- );

-- 7. Join Table for Restaurants and Tags
-- CREATE TABLE restaurant_tags (
--   restaurant_id BIGINT REFERENCES restaurants(id) ON DELETE CASCADE,
--   tag_id BIGINT REFERENCES tags(id) ON DELETE CASCADE,
--   PRIMARY KEY (restaurant_id, tag_id)
-- );

-- ============================================================================
-- SECTION 2: SEARCH FUNCTION (Your existing function)
-- ============================================================================

-- CREATE OR REPLACE FUNCTION search_restaurants(search_term TEXT)
-- RETURNS SETOF restaurants AS $$
-- BEGIN
--   RETURN QUERY
--   SELECT *
--   FROM restaurants
--   WHERE
--     name ILIKE '%' || search_term || '%'
--   OR
--     EXISTS (
--       SELECT 1
--       FROM menu_items
--       WHERE menu_items.restaurant_id = restaurants.id
--       AND menu_items.name ILIKE '%' || search_term || '%'
--     );
-- END;
-- $$ LANGUAGE plpgsql;

-- ============================================================================
-- SECTION 3: NEW ADDITIONS FOR MYEZZ RESTAURANT BACKEND (Run This!)
-- ============================================================================

-- Enable UUID extension (Required for orders table)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 3.1 Create ORDERS Table (Required for Backend Connection & Reports)
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id TEXT UNIQUE NOT NULL,
    customer_name TEXT NOT NULL,
    items JSONB NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN (
            'new', 'preparing', 'ready', 'completed', 'delivered', 'rejected', 'cancelled'
        )
    ),
    verification_code TEXT,
    prep_time INTEGER,
    accepted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3.2 Indexes for Orders (Performance)
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);

-- 3.3 Add Missing Columns to Restaurants (For Profile Page)
ALTER TABLE restaurants 
ADD COLUMN IF NOT EXISTS business_name TEXT,
ADD COLUMN IF NOT EXISTS gstin TEXT;

-- 3.4 Insert Sample Order Data (So Reports have something to show)
INSERT INTO orders (order_id, customer_name, items, total, status, created_at)
VALUES 
  ('ORD-SAMPLE-1', 'Amit Sharma', '[{"name": "Masala Vada Pav", "quantity": 2, "price": 40}]'::jsonb, 80.00, 'delivered', NOW() - INTERVAL '2 hours'),
  ('ORD-SAMPLE-2', 'Sneha Gupta', '[{"name": "Cheese Masala Vada Pav", "quantity": 1, "price": 60}]'::jsonb, 60.00, 'preparing', NOW() - INTERVAL '30 minutes'),
  ('ORD-SAMPLE-3', 'Rahul Verma', '[{"name": "Pav Sandwich (Full) (JAIN)", "quantity": 1, "price": 90}]'::jsonb, 90.00, 'completed', NOW() - INTERVAL '1 day')
ON CONFLICT (order_id) DO NOTHING;

-- ============================================================================
-- SECTION 4: DANGER ZONE (Commented out - DO NOT RUN unless you want to wipe data)
-- ============================================================================

-- TRUNCATE
--   restaurants,
--   cuisines,
--   tags,
--   categories,
--   menu_items,
--   restaurant_cuisines,
--   restaurant_tags
-- RESTART IDENTITY CASCADE;
