-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. RESTAURANTS TABLE
CREATE TABLE IF NOT EXISTS restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    business_name TEXT,
    gstin TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default restaurant
INSERT INTO restaurants (id, name, business_name, gstin)
VALUES (1, 'Patel Juice Centre', 'Patel Enterprises', '27ABCDE1234F1Z5')
ON CONFLICT (id) DO NOTHING;

INSERT INTO restaurants (id, name, business_name, gstin)
VALUES (2, 'BE Bytes', 'BE Bytes Inc', '29XYZAB5678C1Z9')
ON CONFLICT (id) DO NOTHING;


-- 2. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO categories (name) VALUES 
('Starters'), ('Main Course'), ('Beverages'), ('Desserts'), ('Breads')
ON CONFLICT (name) DO NOTHING;


-- 3. MENU ITEMS TABLE
CREATE TABLE IF NOT EXISTS menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT REFERENCES restaurants(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    is_veg BOOLEAN DEFAULT true,
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ORDERS TABLE (from schema.sql)
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id TEXT UNIQUE NOT NULL,
    customer_name TEXT NOT NULL,
    items JSONB NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN (
            'new', 'preparing', 'ready', 'completed', 'delivered', 'rejected', 'cancelled'
        )
    ),
    verification_code TEXT,
    prep_time INTEGER,
    accepted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at);
CREATE INDEX IF NOT EXISTS idx_menu_restaurant ON menu_items (restaurant_id);

-- Sample Data for Menu
INSERT INTO menu_items (restaurant_id, category_id, name, price, is_veg)
SELECT 
    1, 
    c.id, 
    'Mango Juice', 
    120.00, 
    true 
FROM categories c WHERE c.name = 'Beverages'
ON CONFLICT DO NOTHING;

INSERT INTO menu_items (restaurant_id, category_id, name, price, is_veg)
SELECT 
    1, 
    c.id, 
    'Veg Sandwich', 
    80.00, 
    true 
FROM categories c WHERE c.name = 'Starters'
ON CONFLICT DO NOTHING;
